version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: notes_postgres_db
    environment:
      POSTGRES_USER: supercooluser
      POSTGRES_PASSWORD: super_password123
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
