import { test, expect } from '@playwright/test';

test.describe('Notes App E2E Tests', () => {
  
  test.beforeEach(async ({ page }) => {
    // Перед кожним тестом відкриваємо головну сторінку додатка
    await page.goto('/');
  });

  test('should load the page and render head elements', async ({ page }) => {
    // Перевіряємо наявність кнопки зміни мови (шукаємо глобус або текст локалі)
    const langButton = page.locator('button').filter({ hasText: /en|ua/i });
    await expect(langButton).toBeVisible();
  });

  test('should toggle language successfully', async ({ page }) => {
    const langButton = page.locator('button').filter({ hasText: /en|ua/i });
    
    // Спочатку перевіряємо, що у нас стоїть мова за замовчуванням
    const initialText = await langButton.textContent();
    
    // Клікаємо на зміну мови
    await langButton.click();
    
    // Перевіряємо, що значення мови на кнопці змінилося на інше
    const updatedText = await langButton.textContent();
    expect(initialText).not.toBe(updatedText);
  });

  test('should create a new note and display it in the list', async ({ page }) => {
    const timestamp = Date.now();
    const uniqueTitle = `Playwright Test Note ${timestamp}`;
    // Додаємо timestamp до контенту, щоб він також був 100% унікальним при кожному запуску
    const uniqueContent = `This is an automated test note content generated by Playwright ${timestamp}.`;

    // Знаходимо поля введення форми
    const titleInput = page.locator('input[type="text"]');
    const contentInput = page.locator('textarea');
    const submitButton = page.locator('button[type="submit"]');

    // Заповнюємо інпути тестовими даними
    await titleInput.fill(uniqueTitle);
    await contentInput.fill(uniqueContent);

    // Відправляємо форму
    await submitButton.click();

    // Перевіряємо, чи з'явилася створена картка нотатки у списку праворуч
    const noteCard = page.locator('div').filter({ hasText: uniqueTitle });
    await expect(noteCard.first()).toBeVisible();
    
    // Тепер цей селектор гарантовано унікальний і не викличе помилку Strict Mode
    await expect(page.locator(`text=${uniqueContent}`)).toBeVisible();
  });
});