import { test, expect } from '@playwright/test';

test.describe('Notes App E2E Tests', () => {
  
  test.beforeEach(async ({ page }) => {
    // Before each test, open the app's home screen
    await page.goto('/');
  });

  test('should load the page and render head elements', async ({ page }) => {
    // Check for the presence of the language switcher button (looking for globe or locale text)
    const langButton = page.locator('button').filter({ hasText: /en|uk/i });
    await expect(langButton).toBeVisible();
  });

  test('should toggle language successfully', async ({ page }) => {
    const langButton = page.locator('button').filter({ hasText: /en|uk/i });
    
    // First, check that we have the default language set
    const initialText = await langButton.textContent();
    
    // Click to change the language
    await langButton.click();
    
    // Check that the language value on the button has changed to another one
    const updatedText = await langButton.textContent();
    expect(initialText).not.toBe(updatedText);
  });

  test('should create a new note and display it in the list', async ({ page }) => {
    const timestamp = Date.now();
    const uniqueTitle = `Playwright Test Note ${timestamp}`;
    // Add timestamp to content to make it 100% unique on each test run
    const uniqueContent = `This is an automated test note content generated by Playwright ${timestamp}.`;

    // Locate the form input fields
    const titleInput = page.locator('input[type="text"]');
    const contentInput = page.locator('textarea');
    const submitButton = page.locator('button[type="submit"]');

    // Fill inputs with test data
    await titleInput.fill(uniqueTitle);
    await contentInput.fill(uniqueContent);

    // Submit the form
    await submitButton.click();

    // Verify if the created note card appeared in the list on the right
    // Search by the unique title text
    const noteCard = page.locator('div').filter({ hasText: uniqueTitle });
    await expect(noteCard.first()).toBeVisible();
    
    // Now this selector is guaranteed to be unique and will not trigger a Strict Mode error
    await expect(page.locator(`text=${uniqueContent}`)).toBeVisible();
  });
});